services:
  sms-host-protocol:
    build: .
    container_name: sms-host-protocol
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sms-network

  webhook-receiver:
    image: nginx:alpine
    container_name: webhook-receiver
    ports:
      - "8080:80"
    volumes:
      - ./webhook-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sms-host-protocol
    networks:
      - sms-network
    profiles:
      - webhook



networks:
  sms-network:
    driver: bridge



volumes:
  logs:
    driver: local
